### PR TITLE
Added checkbox on posts so that users can mark them as resolved or unresolved

### LINKED ISSUE #4: Add button on posts so that users can mark them as resolved or unresolved
[BACKEND + FRONTEND] Users can change the state of a post by using a frontend UI element and mark it as resolved or unresolved. 

Depends on issues #2 and #3 

Estimated Effort: 1 Week

Acceptance Criteria: 

- User can visually see the current state of the post
- User can change the state of the post from resolved to unresolved
- Once user marks the post from resolved to unresolved on the frontend, post is changed to the correct state on the backend as well. 
- Changed state is maintained even when logging out or changing users.

### PR DESCRIPTION
**Pull request by kujuo**
Resolves #4 

Changes:
- Added frontend checkbox that mirrors the resolved status of the topic.
- Added a socket function to modify the topic resolved state. 
- Added public js for the checkbox. 

Testing:
- Passed local lint
- Passed all local tests previously written.

### CODE REVIEW

**Review by nikkiakali — APPROVED** [review]
Looks good. Passes all tests.

**Review by vasteymnathan — APPROVED** [review]
Passes tests, confirmed that the changes show up on my end!

**Comment by rohini-banerjee** [comment]
Test passes, appears to achieve definition of success from user testing.

**Review by rohini-banerjee — COMMENTED** [review]
Test passes, appears to achieve definition of success from user testing.

**Review by rohini-banerjee — APPROVED** [review]

**Pull request merged**
